export const mockUsers = [
  {
    _id: "user1",
    name: "Alex",
    email: "alex@example.com",
    tasks: [
      "task1",
      "task2",
      "task3",
      "task4",
      "task5",
      "task6",
      "task7",
      "task8",
      "task9",
    ],
  },
  {
    _id: "user2",
    name: "Luca",
    email: "luca@example.com",
    tasks: [
      "task10",
      "task11",
      "task12",
      "task13",
      "task14",
      "task15",
      "task16",
      "task17",
      "task18",
    ],
  },
];

export const mockTasks = [
  {
    _id: "task1",
    title: "Complete Project Proposal",
    description: "Finish the project proposal for the client by EOD.",
    priority: "long",
    dueDate: "today",
    completed: false,
    user: "user1",
  },
  {
    _id: "task2",
    title: "Email Team",
    description: "Send a status update email to the team.",
    priority: "medium",
    dueDate: "today",
    completed: false,
    user: "user1",
  },
  {
    _id: "task3",
    title: "Plan Weekly Schedule",
    description: "Organize tasks and priorities for the week.",
    priority: "medium",
    dueDate: "today",
    completed: false,
    user: "user1",
  },
  {
    _id: "task4",
    title: "Quick Meeting with John",
    description: "Brief sync on current project progress.",
    priority: "short",
    dueDate: "today",
    completed: false,
    user: "user1",
  },
  {
    _id: "task5",
    title: "Coffee Break",
    description: "Take a short coffee break to recharge.",
    priority: "short",
    dueDate: "today",
    completed: false,
    user: "user1",
  },
  {
    _id: "task6",
    title: "Check Emails",
    description: "Go through unread emails in the inbox.",
    priority: "short",
    dueDate: "today",
    completed: false,
    user: "user1",
  },
  {
    _id: "task7",
    title: "Prepare Presentation Slides",
    description: "Draft slides for the next week’s presentation.",
    priority: "medium",
    dueDate: "tomorrow",
    completed: false,
    user: "user1",
  },
  {
    _id: "task8",
    title: "Client Follow-Up Call",
    description: "Follow up with the client on recent feedback.",
    priority: "short",
    dueDate: "tomorrow",
    completed: false,
    user: "user1",
  },
  {
    _id: "task9",
    title: "Brainstorm Ideas for New Project",
    description: "Start brainstorming initial ideas for the new project.",
    priority: "long",
    dueDate: "someday",
    completed: false,
    user: "user1",
  },

  // Luca's tasks
  {
    _id: "task10",
    title: "Finish Report Draft",
    description: "Complete the draft version of the annual report.",
    priority: "long",
    dueDate: "today",
    completed: false,
    user: "user2",
  },
  {
    _id: "task11",
    title: "Update Project Documentation",
    description: "Add recent changes to the project documentation.",
    priority: "medium",
    dueDate: "today",
    completed: false,
    user: "user2",
  },
  {
    _id: "task12",
    title: "Review Design Mockups",
    description: "Look over the latest mockups from the design team.",
    priority: "medium",
    dueDate: "today",
    completed: false,
    user: "user2",
  },
  {
    _id: "task13",
    title: "Prepare Lunch",
    description: "Quickly prepare lunch to stay energized.",
    priority: "short",
    dueDate: "today",
    completed: false,
    user: "user2",
  },
  {
    _id: "task14",
    title: "Order Office Supplies",
    description: "Restock paper and pens for the office.",
    priority: "short",
    dueDate: "today",
    completed: false,
    user: "user2",
  },
  {
    _id: "task15",
    title: "Organize Desk",
    description: "Clean up and organize the desk area.",
    priority: "short",
    dueDate: "today",
    completed: false,
    user: "user2",
  },
  {
    _id: "task16",
    title: "Plan Marketing Campaign",
    description: "Outline initial steps for the upcoming marketing campaign.",
    priority: "medium",
    dueDate: "tomorrow",
    completed: false,
    user: "user2",
  },
  {
    _id: "task17",
    title: "Team Briefing",
    description: "Hold a quick briefing with the team on current tasks.",
    priority: "short",
    dueDate: "tomorrow",
    completed: false,
    user: "user2",
  },
  {
    _id: "task18",
    title: "Research Competitor Products",
    description: "Start analyzing competitors for new ideas.",
    priority: "long",
    dueDate: "someday",
    completed: false,
    user: "user2",
  },
];
